program ACPDV;

{$R *.dres}

uses
  Vcl.Forms,
  ACPDV.View.Principal in 'src\view\ACPDV.View.Principal.pas' {frmPrincipal},
  ACPDV.View.Login in 'src\view\ACPDV.View.Login.pas' {frmLogin},
  ACPDV.View.Componente.Transparencia in 'src\view\componente\ACPDV.View.Componente.Transparencia.pas' {frmBackgroundPreto},
  ACPDV.View.PIX in 'src\view\ACPDV.View.PIX.pas' {framePIX: TFrame},
  ACPDV.View.Dinheiro in 'src\view\ACPDV.View.Dinheiro.pas' {frameDinheiro: TFrame},
  ACPDV.View.Cartao in 'src\view\ACPDV.View.Cartao.pas' {frameCartao: TFrame},
  ACPDV.View.IdentificarCliente in 'src\view\ACPDV.View.IdentificarCliente.pas' {frmIdentificarCliente},
  ACPDV.View.ImportarCliente in 'src\view\ACPDV.View.ImportarCliente.pas' {frmImportarCliente},
  ACPDV.View.AbrirCaixa in 'src\view\ACPDV.View.AbrirCaixa.pas' {frmAbrirCaixa},
  ACPDV.Objeto.AbrirCaixa in 'src\objetos\ACPDV.Objeto.AbrirCaixa.pas',
  ACPDV.View.FecharCaixa in 'src\view\ACPDV.View.FecharCaixa.pas' {frmFecharCaixa},
  ACPDV.View.Componente.ListaPagamentoFechamentoCaixa in 'src\view\componente\ACPDV.View.Componente.ListaPagamentoFechamentoCaixa.pas' {frameComponenteListaFechamentoCaixa: TFrame},
  ACPDV.Objeto.FecharCaixa in 'src\objetos\ACPDV.Objeto.FecharCaixa.pas',
  ACPDV.Objeto.ENum in 'src\objetos\ACPDV.Objeto.ENum.pas',
  ACPDV.Utils.FormHelper in 'src\utils\ACPDV.Utils.FormHelper.pas',
  ACPDV.View.Pagamentos in 'src\view\ACPDV.View.Pagamentos.pas' {frmPagamentos},
  ACPDV.Utils.Utilitarios in 'src\utils\ACPDV.Utils.Utilitarios.pas',
  ACPDV.View.LoginSupervisor in 'src\view\ACPDV.View.LoginSupervisor.pas' {frmLoginSupervisor},
  ACPDV.DataModule.Inferfaces.InterfaceGenericaDAO in 'src\data module\interfaces\ACPDV.DataModule.Inferfaces.InterfaceGenericaDAO.pas',
  ACPDV.DataModule.ConexaoBD in 'src\data module\ACPDV.DataModule.ConexaoBD.pas' {dmDados: TDataModule},
  ACPDV.DataModule.Configuracao in 'src\data module\ACPDV.DataModule.Configuracao.pas',
  ACPDV.Utils.FormsInterfaces in 'src\utils\ACPDV.Utils.FormsInterfaces.pas',
  ACPDV.Utils.TratamentoExceptions in 'src\utils\ACPDV.Utils.TratamentoExceptions.pas',
  ACPDV.Utils.Impl.Forms in 'src\utils\impl\ACPDV.Utils.Impl.Forms.pas',
  ACPDV.Utils.Impl.GerenciadorForm in 'src\utils\impl\ACPDV.Utils.Impl.GerenciadorForm.pas',
  ACPDV.Utils.Impl.ResourcesImages in 'src\utils\impl\ACPDV.Utils.Impl.ResourcesImages.pas',
  ACPDV.View.CentralMensagens in 'src\view\ACPDV.View.CentralMensagens.pas' {frmCentralMensagens},
  ACPDV.View.Componente.ItemListaProduto in 'src\view\componente\ACPDV.View.Componente.ItemListaProduto.pas' {frameComponenteListaItem: TFrame},
  ACPDV.Objeto.Adquirente in 'src\objetos\ACPDV.Objeto.Adquirente.pas',
  ACPDV.DataModule.DAO.Adquirente in 'src\data module\dao\ACPDV.DataModule.DAO.Adquirente.pas',
  ACPDV.Objeto.CaixaMovimento in 'src\objetos\ACPDV.Objeto.CaixaMovimento.pas',
  ACPDV.DataModule.DAO.CaixaMovimento in 'src\data module\dao\ACPDV.DataModule.DAO.CaixaMovimento.pas',
  ACPDV.Objeto.Caixa in 'src\objetos\ACPDV.Objeto.Caixa.pas',
  ACPDV.DataModule.DAO.Caixa in 'src\data module\dao\ACPDV.DataModule.DAO.Caixa.pas',
  ACPDV.Objeto.CartaoBandeira in 'src\objetos\ACPDV.Objeto.CartaoBandeira.pas',
  ACPDV.DataModule.DAO.CartaoBandeira in 'src\data module\dao\ACPDV.DataModule.DAO.CartaoBandeira.pas',
  ACPDV.Objeto.CEST in 'src\objetos\ACPDV.Objeto.CEST.pas',
  ACPDV.DataModule.DAO.CEST in 'src\data module\dao\ACPDV.DataModule.DAO.CEST.pas',
  ACPDV.Objeto.Cidade in 'src\objetos\ACPDV.Objeto.Cidade.pas',
  ACPDV.DataModule.DAO.Cidade in 'src\data module\dao\ACPDV.DataModule.DAO.Cidade.pas',
  ACPDV.Objeto.CodigoANP in 'src\objetos\ACPDV.Objeto.CodigoANP.pas',
  ACPDV.DataModule.DAO.CodigoANP in 'src\data module\dao\ACPDV.DataModule.DAO.CodigoANP.pas',
  ACPDV.Objeto.CRT in 'src\objetos\ACPDV.Objeto.CRT.pas',
  ACPDV.Objeto.Configuracao in 'src\objetos\ACPDV.Objeto.Configuracao.pas',
  ACPDV.Objeto.CST in 'src\objetos\ACPDV.Objeto.CST.pas',
  ACPDV.Objeto.CSTCOFINS in 'src\objetos\ACPDV.Objeto.CSTCOFINS.pas',
  ACPDV.Objeto.CSTIPI in 'src\objetos\ACPDV.Objeto.CSTIPI.pas',
  ACPDV.Objeto.CSTPIS in 'src\objetos\ACPDV.Objeto.CSTPIS.pas',
  ACPDV.Objeto.Empresa in 'src\objetos\ACPDV.Objeto.Empresa.pas',
  ACPDV.Objeto.FormaPagamento in 'src\objetos\ACPDV.Objeto.FormaPagamento.pas',
  ACPDV.Objeto.IBPT in 'src\objetos\ACPDV.Objeto.IBPT.pas',
  ACPDV.Objeto.MFEPagamento in 'src\objetos\ACPDV.Objeto.MFEPagamento.pas',
  ACPDV.Objeto.NFE in 'src\objetos\ACPDV.Objeto.NFE.pas',
  ACPDV.Objeto.NFEEvento in 'src\objetos\ACPDV.Objeto.NFEEvento.pas',
  ACPDV.Objeto.NFEInutilizacao in 'src\objetos\ACPDV.Objeto.NFEInutilizacao.pas',
  ACPDV.Objeto.NFEItem in 'src\objetos\ACPDV.Objeto.NFEItem.pas',
  ACPDV.Objeto.NFEPagamento in 'src\objetos\ACPDV.Objeto.NFEPagamento.pas',
  ACPDV.Objeto.Operador in 'src\objetos\ACPDV.Objeto.Operador.pas',
  ACPDV.Objeto.Origem in 'src\objetos\ACPDV.Objeto.Origem.pas',
  ACPDV.Objeto.Pessoa in 'src\objetos\ACPDV.Objeto.Pessoa.pas',
  ACPDV.Objeto.POS in 'src\objetos\ACPDV.Objeto.POS.pas',
  ACPDV.Objeto.Produto in 'src\objetos\ACPDV.Objeto.Produto.pas',
  ACPDV.Objeto.SuprimentoSangria in 'src\objetos\ACPDV.Objeto.SuprimentoSangria.pas',
  ACPDV.Objeto.Turno in 'src\objetos\ACPDV.Objeto.Turno.pas',
  ACPDV.Objeto.UF in 'src\objetos\ACPDV.Objeto.UF.pas',
  ACPDV.Objeto.Unidade in 'src\objetos\ACPDV.Objeto.Unidade.pas',
  ACPDV.DataModule.DAO.Configuracao in 'src\data module\dao\ACPDV.DataModule.DAO.Configuracao.pas',
  ACPDV.DataModule.DAO.CRT in 'src\data module\dao\ACPDV.DataModule.DAO.CRT.pas',
  ACPDV.DataModule.DAO.CST in 'src\data module\dao\ACPDV.DataModule.DAO.CST.pas',
  ACPDV.DataModule.DAO.CSTCOFINS in 'src\data module\dao\ACPDV.DataModule.DAO.CSTCOFINS.pas',
  ACPDV.DataModule.DAO.CSTIPI in 'src\data module\dao\ACPDV.DataModule.DAO.CSTIPI.pas',
  ACPDV.DataModule.DAO.CSTPIS in 'src\data module\dao\ACPDV.DataModule.DAO.CSTPIS.pas',
  ACPDV.DataModule.DAO.Empresa in 'src\data module\dao\ACPDV.DataModule.DAO.Empresa.pas',
  ACPDV.DataModule.DAO.FormaPagamento in 'src\data module\dao\ACPDV.DataModule.DAO.FormaPagamento.pas',
  ACPDV.DataModule.DAO.IBPT in 'src\data module\dao\ACPDV.DataModule.DAO.IBPT.pas',
  ACPDV.DataModule.DAO.MFEPagamento in 'src\data module\dao\ACPDV.DataModule.DAO.MFEPagamento.pas',
  ACPDV.DataModule.DAO.Operador in 'src\data module\dao\ACPDV.DataModule.DAO.Operador.pas',
  ACPDV.DataModule.Operador in 'src\data module\ACPDV.DataModule.Operador.pas' {dmOperador: TDataModule},
  ACPDV.Controller in 'src\controller\ACPDV.Controller.pas',
  ACPDV.DataModule.DAO.Turno in 'src\data module\dao\ACPDV.DataModule.DAO.Turno.pas';

{$R *.res}

begin
  Application.Initialize;
  ReportMemoryLeaksOnShutdown := True;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.Run;
end.
